<div class="page-header">
  <h1>List users</h1>
</div>
<?php
if($this->message){
	echo "CAMPI DA COMPILARE: <br><font color=\"red\">";
foreach ($this->message as $key => $value) {
 		   				echo $key.", ";
	}
	echo "</font>";
}
?>

<p align="right"><a href="/admin/add">AGGIUNGI UN NUOVO UTENTE</a></p>
<table class="table">
    <thead>
      <tr>
      	<th>#</th>
        <th>Username</th>
        <th>Password (sh1)</th>
        <th>Role</th>
        <th>Data d'iscrizione</th>
        <th>Mod</th>
        <th>Del</th>
      </tr>
    </thead>
    <tbody>
<?php

if($this->users) {
		foreach ($this->users as $user) {
			?>
			<tr>
        <td><?php echo $user['id']; ?></td>
        <td><?php echo $user['username']; ?></td>
        <td><?php echo $user['password']; ?></td>
        <td><?php echo $user['role']; ?></td>
        <td><?php echo $user['date_created']; ?></td>
        <td><?php echo "<a href=\"/admin/user/".$user['id']."\">Mod</a>"; ?></td>
        <td><?php echo "<a href=\"/admin/del_user/".$user['id']."\">Del</a>"; ?></td>
      	</tr>

<?php
		}
}

?>
    </tbody>
  </table>