<div class="page-header">
  <h1>Profilo: <b><?php echo $this->name; ?></b></h1>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Scheda dell'utente</h3>
  </div>
  <div class="panel-body">


  	<div class="row">
  <div class="col-md-6">
 <b>Nome:</b> <?php echo $this->name; ?><br>
   <b>Ruolo:</b> <?php echo $this->ruolo; ?><br>
   <b>Data d'iscrizione:</b> <?php echo $this->giorno; ?>

  </div>
  <div class="col-md-6">
<?php
$id = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');

  	if($this->hasAvatar($id)) {
  		?>
  		<center><img src="/tmp/file-<?php echo $id; ?>.jpg" width="100" height="100"></img></center>
  		<?php
  	}

?>

  </div>
  
  </div>
</div>
</div>

